-- backend/database/sample_data.sql
-- このファイルはGit管理されるため、個人のメールアドレスなど公開したくない情報は書かないこと。
--
-- ログインを許可するユーザーは、Git管理外の backend/database/local_users.sql に登録してください。
-- (init_db.py が存在すれば自動で読み込みます。無ければ以下の例を参考に自分で作成してください)
--
-- 例: backend/database/local_users.sql
-- INSERT INTO APP_USER (email, name) VALUES ('you@example.com', 'あなたの名前');
